apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: k8sdocker2
      containers:
        - name: nginx
          image: openjdk:17.0.2-jdk-oracle
#          ports:
#            - containerPort: 80
